// Jolt Physics Library (https://github.com/jrouwe/JoltPhysics)
// SPDX-FileCopyrightText: 2021 Jorrit Rouwe
// SPDX-License-Identifier: MIT

// Note: Order is important, an enum is created and its value is stored in a binary stream!
MOSS_DECLARE_PRIMITIVE(uint8)
MOSS_DECLARE_PRIMITIVE(uint16)
MOSS_DECLARE_PRIMITIVE(int)
MOSS_DECLARE_PRIMITIVE(uint32_t)
MOSS_DECLARE_PRIMITIVE(uint64)
MOSS_DECLARE_PRIMITIVE(float)
MOSS_DECLARE_PRIMITIVE(bool)
MOSS_DECLARE_PRIMITIVE(String)
MOSS_DECLARE_PRIMITIVE(Float3)
MOSS_DECLARE_PRIMITIVE(Vec3)
MOSS_DECLARE_PRIMITIVE(Vec4)
MOSS_DECLARE_PRIMITIVE(Quat)
MOSS_DECLARE_PRIMITIVE(Mat44)
MOSS_DECLARE_PRIMITIVE(double)
MOSS_DECLARE_PRIMITIVE(DVec3)
MOSS_DECLARE_PRIMITIVE(DMat44)
MOSS_DECLARE_PRIMITIVE(Double3)
MOSS_DECLARE_PRIMITIVE(Float4)
MOSS_DECLARE_PRIMITIVE(UVec4)

#undef MOSS_DECLARE_PRIMITIVE
