// Jolt Physics Library (https://github.com/jrouwe/JoltPhysics)
// SPDX-FileCopyrightText: 2021 Jorrit Rouwe
// SPDX-License-Identifier: MIT

#pragma once

#include <Moss/Resources/ObjectStream/SerializableObject.h>
#include <Moss/Core/Color.h>
#include <Moss/Geometry/AABox.h>
#include <Moss/Geometry/Triangle.h>
#include <Moss/Geometry/IndexedTriangle.h>

MOSS_NAMESPACE_BEGIN

MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, uint8);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, uint16);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, int);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, uint32);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, uint64);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, float);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, double);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, bool);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, String);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, Float3);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, Float4);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, Double3);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, Vec3);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, DVec3);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, Vec4);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, UVec4);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, Quat);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, Mat44);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_EXPORT, DMat44);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_EXPORT, Color);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_EXPORT, AABox);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_EXPORT, Triangle);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_EXPORT, IndexedTriangleNoMaterial);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_EXPORT, IndexedTriangle);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_EXPORT, Plane);

MOSS_NAMESPACE_END

// These need to be added after all types have been registered or else clang under linux will not find GetRTTIOfType for the type
#include <Moss/Resources/ObjectStream/SerializableAttributeTyped.h>
#include <Moss/Resources/ObjectStream/SerializableAttributeEnum.h>
