// Jolt Physics Library (https://github.com/jrouwe/JoltPhysics)
// SPDX-FileCopyrightText: 2021 Jorrit Rouwe
// SPDX-License-Identifier: MIT

#pragma once

#include <Moss/Resources/ObjectStream/SerializableObject.h>
#include <Moss/Core/Color.h>
#include <Moss/Geometry/AABox.h>
#include <Moss/Geometry/Triangle.h>
#include <Moss/Geometry/IndexedTriangle.h>

MOSS_SUPPRESS_WARNINGS_END

MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, uint8);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, uint16);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, int);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, uint32_t);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, uint64);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, float);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, double);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, bool);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, String);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, Float3);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, Float4);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, Double3);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, Vec3);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, DVec3);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, Vec4);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, UVec4);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, Quat);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, Mat44);
MOSS_DECLARE_RTTI_OUTSIDE_CLASS(MOSS_API, DMat44);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_API, Color);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_API, AABox);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_API, Triangle);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_API, IndexedTriangleNoMaterial);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_API, IndexedTriangle);
MOSS_DECLARE_SERIALIZABLE_OUTSIDE_CLASS(MOSS_API, Plane);

MOSS_SUPPRESS_WARNINGS_END

// These need to be added after all types have been registered or else clang under linux will not find GetRTTIOfType for the type
#include <Moss/Resources/ObjectStream/SerializableAttributeTyped.h>
#include <Moss/Resources/ObjectStream/SerializableAttributeEnum.h>
