// Jolt Physics Library (https://github.com/jrouwe/JoltPhysics)
// SPDX-FileCopyrightText: 2021 Jorrit Rouwe
// SPDX-License-Identifier: MIT

#include <Moss/Resources/ObjectStream/TypeDeclarations.h>

MOSS_NAMESPACE_BEGIN

MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(uint8)			{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(uint16)		{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(int)			{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(uint32)		{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(uint64)		{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(float)			{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(double)		{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(bool)			{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(String)		{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(Float3)		{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(Float4)		{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(Double3)		{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(Vec3)			{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(DVec3)			{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(Vec4)			{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(UVec4)			{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(Quat)			{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(Mat44)			{ }
MOSS_IMPLEMENT_RTTI_OUTSIDE_CLASS(DMat44)		{ }

MOSS_IMPLEMENT_SERIALIZABLE_OUTSIDE_CLASS(Color)
{
	MOSS_ADD_ATTRIBUTE(Color, r)
	MOSS_ADD_ATTRIBUTE(Color, g)
	MOSS_ADD_ATTRIBUTE(Color, b)
	MOSS_ADD_ATTRIBUTE(Color, a)
}

MOSS_IMPLEMENT_SERIALIZABLE_OUTSIDE_CLASS(AABox)
{
	MOSS_ADD_ATTRIBUTE(AABox, mMin)
	MOSS_ADD_ATTRIBUTE(AABox, mMax)
}

MOSS_IMPLEMENT_SERIALIZABLE_OUTSIDE_CLASS(Triangle)
{
	MOSS_ADD_ATTRIBUTE(Triangle, mV)
	MOSS_ADD_ATTRIBUTE(Triangle, mMaterialIndex)
	MOSS_ADD_ATTRIBUTE(Triangle, mUserData)
}

MOSS_IMPLEMENT_SERIALIZABLE_OUTSIDE_CLASS(IndexedTriangleNoMaterial)
{
	MOSS_ADD_ATTRIBUTE(IndexedTriangleNoMaterial, mIdx)
}

MOSS_IMPLEMENT_SERIALIZABLE_OUTSIDE_CLASS(IndexedTriangle)
{
	MOSS_ADD_BASE_CLASS(IndexedTriangle, IndexedTriangleNoMaterial)

	MOSS_ADD_ATTRIBUTE(IndexedTriangle, mMaterialIndex)
	MOSS_ADD_ATTRIBUTE(IndexedTriangle, mUserData)
}

MOSS_IMPLEMENT_SERIALIZABLE_OUTSIDE_CLASS(Plane)
{
	MOSS_ADD_ATTRIBUTE(Plane, mNormalAndConstant)
}

MOSS_NAMESPACE_END
